### ISSUE TITLE
Java vulnerability...

### ISSUE THREAD

**Issue by coderpop** [arduino/arduino-cvd-policy#3]
Thank you for this! The last time I reported a java vulnerability it was largerly ignored and swpet under the carpet - I hope now we have a new era of openess and honesty.....

Here is the report from a scan by Kaspersky Internet Security 18.0.0.405(j)

https://threats.kaspersky.com/en/vulnerability/KLA11294/?utm_source=KIS_18.0.0&utm_medium=inp&utm_campaign=en-gb

I installed arduino IDE 1.8.7 fresh this morning so it seems to be a current threat with the packaged version of Java.

Coderpop.

**Comment by gvarisco** [comment]
Thank you for reaching out, @coderpop. I'll pass this to our development team and get back to you once I've an update. As mentioned in the policy, please use security@arduino.cc for reporting issues.

Best regards,

Gian

**Comment by gvarisco** [comment]
Hey @coderpop,
thanks again for opening this issue. We've upgraded the JRE version to 8u192 on our build system and our hourly builds are now (as we speak) built against it. You can find them on https://www.arduino.cc/en/Main/Software#hourly 

Beta IDE builds are also updated to reflect the JRE upgrade. We'll soon release a new stable version.
